// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAet75QRBn5VUOSSKDFCPX3Sat8akMQcuk',
    appId: '1:822696102524:web:954f800e9a8ea0c00817f9',
    messagingSenderId: '822696102524',
    projectId: 'periche-tg-shop',
    authDomain: 'periche-tg-shop.firebaseapp.com',
    storageBucket: 'periche-tg-shop.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6RxtURK00Q98mIAb0mx8ZUcQOU6uLIcU',
    appId: '1:822696102524:android:a708d60845f1f4830817f9',
    messagingSenderId: '822696102524',
    projectId: 'periche-tg-shop',
    storageBucket: 'periche-tg-shop.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFLLdrOaBKwEPgSlJPrJwR-HOXfVNDzG8',
    appId: '1:822696102524:ios:b24d1e4bac30709a0817f9',
    messagingSenderId: '822696102524',
    projectId: 'periche-tg-shop',
    storageBucket: 'periche-tg-shop.firebasestorage.app',
    iosBundleId: 'com.example.perShop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFLLdrOaBKwEPgSlJPrJwR-HOXfVNDzG8',
    appId: '1:822696102524:ios:b24d1e4bac30709a0817f9',
    messagingSenderId: '822696102524',
    projectId: 'periche-tg-shop',
    storageBucket: 'periche-tg-shop.firebasestorage.app',
    iosBundleId: 'com.example.perShop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAet75QRBn5VUOSSKDFCPX3Sat8akMQcuk',
    appId: '1:822696102524:web:36619e1e6809eb5a0817f9',
    messagingSenderId: '822696102524',
    projectId: 'periche-tg-shop',
    authDomain: 'periche-tg-shop.firebaseapp.com',
    storageBucket: 'periche-tg-shop.firebasestorage.app',
  );
}
